/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_xuyaofeng_myapplication_JniTest */

#ifndef _Included_com_example_xuyaofeng_myapplication_JniTest
#define _Included_com_example_xuyaofeng_myapplication_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_xuyaofeng_myapplication_JniTest
 * Method:    getNativeString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_xuyaofeng_myapplication_JniTest_getNativeString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
